README.md
dev/README.md
dev/src/.properties
dev/src/BaselineOfExercism/BaselineOfExercism.class.st
dev/src/BaselineOfExercism/package.st
dev/src/Exercism/HelloWorld.class.st
dev/src/Exercism/HelloWorldTest.class.st
dev/src/Exercism/package.st
dev/src/ExercismTools/ClyExercismSubmitCommand.class.st
dev/src/ExercismTools/package.st
dev/src/XercismTools/AbstractNautilusUI.extension.st
dev/src/XercismTools/ExTonelWriter.class.st
dev/src/XercismTools/ExercismManager.class.st
dev/src/XercismTools/ExercismManagerTests.class.st
dev/src/XercismTools/package.st
docs/INSTALLATION.md

… example while we sort things out
fixes #17

Move exercism student tools to repo

---

config.json
exercises/HelloWorld/HelloWorld.class.st

As per comments from @samWson about domain class naming in tests and not wanting to make our generator too complicated

Improve lint checker regex (Go compatible), so it fixes #25

---

README.md
docs/ABOUT.md
docs/INSTALLATION.md
docs/SNIPPET.txt
docs/TESTS.md

Had some time on the train with an iPad so focused on readability and trying to streamline the docs a bit.

Documentation refactoring

---

dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismTools/ExercismManager.class.st

Remember the last generated path (so regeneration is less painful)
Use RPackage organizer as per code review

Fix the  generator to handle package tags vs. packages

---

dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismDev/ExercismGeneratorTests.class.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/String.extension.st

This fixes new-user welcome initial hello world submission

Fix newuser welcome - proper exercise submission

---

dev/src/ExercismTools/AbstractNautilusUI.extension.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/RPackage.extension.st
dev/src/ExercismTools/RPackageTag.extension.st

Getting close, but still a few rough edges

Properly handle user submission

---

dev/src/ExercismTools/Path.extension.st

Fix pathString which used another missing method

---

dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismTools/ExercismManager.class.st

Improve shell error reporting

---

dev/src/ExercismTools/DoesNotUnderstandDebugAction.extension.st
dev/src/ExercismTools/OCUndeclaredVariableWarning.extension.st
dev/src/ExercismTools/PreDebugDoesNotUnderstandAction.extension.st
dev/src/ExercismTools/SugsGlamourCodeContext.extension.st
dev/src/ExercismTools/TAssertable.extension.st

Fix refactoring in the debugger
Fix missing deny:equals for testing

Fix environment issues in Pharo 6.1 that user may encounter

---

config/exercise_readme.go.tmpl
exercises/hello-world/README.md
exercises/reverse-string/README.md
exercises/two-fer/README.md

From experience of Serge when he jumped in to give it a go.

improved generator template and readme's

---

dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismTools/AbstractNautilusUI.extension.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/Welcome.class.st

A small cleanup to set a better example (still need some better tests though)

Code cleanup (use proper objects and not class methods.

---

dev/src/Exercism/HelloWorld.class.st
dev/src/Exercism/HelloWorldTest.class.st
dev/src/Exercism/ReverseStringTest.class.st
dev/src/Exercism/TwoFer.class.st
dev/src/Exercism/TwoFerTest.class.st

When creating Leap - I spotted that we hadn't categorised consistently, so I think this is better example - tests in #testing, the sample class in #exercise.
Give it a review and see if you guys agree

Initial exercises - categorisation consistency improvements, small tweaks to readme text

---

config/maintainers.json

Add bencoman entry

---

config/maintainers.json

issue-72: Add samWson's details

---

docs/INSTALLATION.md

Intended for users who are not using a UNIX style shell.

Add Windows installation instructions

---

dev/src/ExercismTools/AbstractNautilusUI.extension.st

I had trouble seeing the menu item when was near the bottom.

Move "Exercism" package menu to top.

---

dev/src/ExercismTools/AbstractNautilusUI.extension.st
dev/src/ExercismTools/ExercismDownloader.class.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/MorphicUIManager.extension.st
dev/src/ExercismTools/StaticTextMorph.class.st
dev/src/ExercismTools/TextEntryDialogWindow.extension.st
dev/src/ExercismTools/UITheme.extension.st

In the dialog box requesting the user enter their Exercism student token, provide a clickable link to get this from the Exercism Settings web page.
Testing from playground... ```ExercismDownloader configureToken```

Clickable link to token

---

dev/src/ExercismTools/ExercismCommand.class.st
dev/src/ExercismTools/ExercismDownload.class.st

After refactoring to facilitate a unit test for instance side, I missed fixing class side to match.
btw, also now doesn't require #welcome to be run.  Creates "Exercism" package on demand.
https://github.com/exercism/pharo/compare/fix-ExercismDownload-for-real?expand=1#diff-8b0cdc2f98af299a90c80cf87795dc61R90

Fix ExercismDownload for real.

---

dev/src/ExercismTools/ExercismSubmit.class.st
dev/src/ExercismTools/ExercismSubmitTest.class.st

For Issue #96, an extra option to get solution data for given class.

Retrieve metadata for class.

---

README.md
exercises/reverse-string/README.md

Adding a relevant section from the 'Reading Smalltalk' PDF. I've picked this part as it seems the appropriate place for it.
Let me know if you think this style of using sections of the PDF through out the exercises is the right approach or if we should do something else.
One part of many possible changes for #83.

Add exscript from Reading Smalltalk PDF

---

docs/INSTALLATION.md
docs/SNIPPET.txt

More readme corrections for Windows users

Update readme for pharo smalltalk repo name #2

---

dev/src/ExercismTools/ClyExercismCommand.class.st
dev/src/ExercismTools/ClyExercismExerciseCommand.class.st
dev/src/ExercismTools/ClyExercismMenuGroup.class.st
dev/src/ExercismTools/ClyExercismPkgFetchCommand.class.st
dev/src/ExercismTools/ClyExercismProgressCommand.class.st
dev/src/ExercismTools/ClyExercismSubmitCommand.class.st
dev/src/ExercismTools/ClyExercismTagFetchCommand.class.st

Builds on the improved menus and refactors the method categorisation as well as some slight simplification

Improved fetch menus with cleanup

---

dev/src/ExercismDev/ClyExercismGenerateCommand.class.st
dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismTools/ExTonelWriter.class.st

(cherry picked from commit ba7242d)
This PR fixes some fork shenanigans and gives a clean diff of the code required.

Adds generator menu commands and updates it to work with the latest Tonel

---

dev/src/ExercismTools/ClyExercismCommand.class.st
dev/src/ExercismTools/ClyExercismExerciseCommand.class.st
dev/src/ExercismTools/ClyExercismMenuGroup.class.st
dev/src/ExercismTools/ClyExercismMetaDataCommand.class.st
dev/src/ExercismTools/ClyExercismPkgFetchCommand.class.st
dev/src/ExercismTools/ClyExercismProgressCommand.class.st
dev/src/ExercismTools/ClyExercismSubmitCommand.class.st
dev/src/ExercismTools/ClyExercismTagFetchCommand.class.st

Recovers lots changes by incorrect PR merge order

Improved fetch menus

---

dev/src/BaselineOfExercism/BaselineOfExercism.class.st
dev/src/Exercism/Acronym.class.st
dev/src/Exercism/AcronymTest.class.st
dev/src/Exercism/HelloWorld.class.st
dev/src/Exercism/HelloWorldTest.class.st
dev/src/Exercism/Leap.class.st
dev/src/Exercism/LeapTest.class.st
dev/src/Exercism/ReverseString.class.st
dev/src/Exercism/ReverseStringTest.class.st
dev/src/Exercism/SumOfMultiples.class.st
dev/src/Exercism/SumOfMultiplesTest.class.st
dev/src/Exercism/TwoFerTest.class.st
dev/src/ExercismDev/ExercismExerciseGenerator.class.st
dev/src/ExercismDev/ExercismExerciseGeneratorTest.class.st
dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismDev/String.extension.st
dev/src/ExercismTools/ExercismTest.class.st
dev/src/ExercismTools/ExercismTestTest.class.st
dev/src/ExercismTools/Welcome.class.st
dev/src/ExercismWIP/HammingTest.class.st
dev/src/ExercismWIP/SpaceAgeTest.class.st
dev/src/ExercismWIP/package.st

This is the suggested merge for #144 
(I 'm running through my fork, just to practice what would happen if this was on the pharo-project repo where you don't have write access)

Macta generate exercises from spec

---

dev/src/Exercism/AcronymTest.class.st
dev/src/Exercism/HelloWorldTest.class.st
dev/src/Exercism/LeapTest.class.st
dev/src/Exercism/ReverseStringTest.class.st
dev/src/Exercism/SumOfMultiplesTest.class.st
dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismTools/ExercismTestTest.class.st

Fix the failing followedBy test due to test re-arrangment

---

dev/src/Exercism/Hamming.class.st
dev/src/Exercism/HammingTest.class.st

Test using new submission process

New Hamming Test

---

dev/src/Exercism/Hamming.class.st
dev/src/Exercism/HammingTest.class.st
dev/src/Exercism/HelloWorldTest.class.st
dev/src/Exercism/LeapTest.class.st
dev/src/Exercism/SumOfMultiples.class.st
dev/src/Exercism/TwoFerTest.class.st

Small improvements to the exercises and meta data

Misc Small improvements to solutions and topics

---

dev/src/ExercismDev/ClyExercismVisualizeCommand.class.st
dev/src/ExercismDev/ExercismExercise.class.st
dev/src/ExercismDev/ExercismManager.extension.st
dev/src/ExercismTools/ExercismTest.class.st

Help see the relationships between exercises

Simple Exercise visualisation to see ordering and dependency

---

dev/src/Exercism/AcronymTest.class.st
dev/src/Exercism/Hamming.class.st
dev/src/Exercism/HammingTest.class.st
dev/src/Exercism/LeapTest.class.st
dev/src/Exercism/ReverseStringTest.class.st
dev/src/Exercism/SumOfMultiples.class.st
dev/src/Exercism/SumOfMultiplesTest.class.st
dev/src/Exercism/TwoFerTest.class.st
dev/src/ExercismDev/ExercismExerciseGenerator.class.st
dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismTools/ExercismTest.class.st
dev/src/ExercismTools/ManifestExercismTools.class.st

Fix generator to handle numbering format for nested cases

Update existing tests to new number format

---

dev/src/Exercism/HammingTest.class.st
dev/src/Exercism/HelloWorldTest.class.st
dev/src/Exercism/RaindropsTest.class.st
dev/src/Exercism/TwoFerTest.class.st
dev/src/ExercismDev/ExercismConfigGenerator.class.st
dev/src/ExercismDev/ExercismExercise.class.st
dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismDev/ExercismManager.extension.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/ExercismTest.class.st
dev/src/ExercismTools/ExercismTestTest.class.st
dev/src/ExercismTools/STONJSONWriter.class.st

An sort of spike to generate the required json config file for the exercises.

Auto generate config files

---

dev/src/Exercism/AcronymTest.class.st
dev/src/Exercism/HammingTest.class.st
dev/src/Exercism/HelloWorldTest.class.st
dev/src/Exercism/LeapTest.class.st
dev/src/Exercism/RaindropsTest.class.st
dev/src/Exercism/ReverseStringTest.class.st
dev/src/Exercism/SpaceAgeTest.class.st
dev/src/Exercism/SumOfMultiplesTest.class.st
dev/src/Exercism/TwoFerTest.class.st
dev/src/ExercismDev/ExercismConfigGenerator.class.st
dev/src/ExercismDev/ExercismExercise.class.st
dev/src/ExercismDev/ExercismExerciseTest.class.st
dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismTools/ExercismTest.class.st
dev/src/ExercismTools/ExercismTestTest.class.st

This improves how meta information for exercises is specified (not via class methods on the exercise test, apart from version and uuid which are generated from the spec)

Improved exercism exercise model

---

README.md

Update the project readme to better reflect contribution instructions

---

config.json
dev/src/Exercism/WordCount.class.st
dev/src/Exercism/WordCountTest.class.st
dev/src/ExercismDev/ExercismManager.extension.st
docs/ABOUT.md
exercises/word-count/.meta/hints.md
exercises/word-count/.meta/solution/WordCount.class.st
exercises/word-count/README.md
exercises/word-count/WordCountTest.class.st

This solution has an alternative (categorised) - we might want to flag these in the future when we get mentor tools running

Word count exercise

---

dev/src/Exercism/Binary.class.st
dev/src/Exercism/BinaryTest.class.st
dev/src/Exercism/Sieve.class.st
dev/src/Exercism/SieveTest.class.st
dev/src/Exercism/SpaceAgeTest.class.st
dev/src/ExercismTools/ExercismTest.class.st

Have started to add a #generator hint to tests if I rename the solution method (with a view to re-generation at some point)

Implementations for Sieve and Binary exercises

---

dev/src/ExercismTests/ExercismExerciseTest.class.st
dev/src/ExercismTools/ClyExercismCommand.class.st
dev/src/ExercismTools/ClyExercismFetchCommand.class.st
dev/src/ExercismTools/ClyExercismSubmitCommand.class.st
dev/src/ExercismTools/ExercismDownloadCommand.class.st
dev/src/ExercismTools/ExercismExercise.class.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/ExercismSubmission.class.st

For some reason - the create branch from issue seems to branch from a strange place...

58 loading a new exercise doesnt automatically select it

---

dev/src/ExercismTools/ExercismManager.class.st

The create branch from issue - seemed to lose this work for some reason. Bringing it back

198 recover this branch

---

dev/src/ExercismTests/ExercismSubmissionTest.class.st
dev/src/ExercismTools/ClyExercismExerciseCommand.class.st
dev/src/ExercismTools/ClyExercismFetchCommand.class.st
dev/src/ExercismTools/ClyExercismSubmitCommand.class.st
dev/src/ExercismTools/ExercismSubmission.class.st

Recovery from mis-merge of #199

Report an error if failure on download command

---

dev/src/ExercismTests/ExercismSubmissionTest.class.st
dev/src/ExercismTools/ClyExercismExerciseCommand.class.st
dev/src/ExercismTools/ClyExercismFetchCommand.class.st
dev/src/ExercismTools/ClyExercismSubmitCommand.class.st
dev/src/ExercismTools/ExercismDownloadCommand.class.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/ExercismSubmission.class.st

detect real reason for failure correctly

---

dev/src/ExercismTools/ExercismDownloadCommand.class.st
dev/src/ExercismTools/ExercismSubmitCommand.class.st

Raise error correctly

---

dev/src/ExercismDev/String.extension.st
dev/src/ExercismTools/ClyExercismExerciseCommand.class.st
dev/src/ExercismTools/ClyExercismFetchCommand.class.st
dev/src/ExercismTools/ClyExercismSubmitCommand.class.st
dev/src/ExercismTools/ExercismDownloadCommand.class.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/ExercismSubmission.class.st
dev/src/ExercismTools/String.extension.st

Cleans up the error reporting slightly

Catch model errors and report them via an abort box

---

dev/src/Exercism/ResultTally.class.st
dev/src/Exercism/Tournament.class.st
dev/src/Exercism/TournamentTest.class.st

Tournament exercise
@samWson @bencoman - this one is even meatier than grade-school, and I had to mull it over for half an hour to decide how to tackle it. There are lots of ways to solve it (and looking back at some of the other oo languages like ruby and python - they didn't use any objects at all). However I think my solution nicely encapsulates behaviour without going to far.
My only trick is to use a lookup table to provide an inverse outcome, that really simplifies things. Not spotted anyone else doing that.

Tournament exercise

---

config.json
dev/src/Exercism/Etl.class.st
dev/src/Exercism/EtlTest.class.st
dev/src/ExercismDev/ClyExercismGenerateCommand.class.st
dev/src/ExercismDev/ClyExercismVisualizeCommand.class.st
dev/src/ExercismDev/ExercismExerciseGenerator.class.st
exercises/etl/.meta/hints.md
exercises/etl/.meta/solution/Etl.class.st
exercises/etl/EtlTest.class.st
exercises/etl/README.md

Adds the generate command to the world menu (so its a bit easier to generate the exercism meta data files).
Note - relies on separate Exercism PR to to update the Etl problem specification to be a 1 parameter data spec.

Etl exercise

---

dev/src/ExercismTests/ExercismExerciseTest.class.st
dev/src/ExercismTools/ClyExercismFetchCommand.class.st
dev/src/ExercismTools/ExercismExercise.class.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/ExercismTest.class.st
dev/src/ExercismTools/TestResult.extension.st

Publish the test results with the solution

Publish test results

---

docs/TESTS.md

As per Ben's concern in #223 - we hadn't previously documented why we have testXX_ methods. 
@bencoman see if this helps a bit

Improve the testing documentation

---

dev/src/Exercism/BracketPush.class.st

Add a comment

---

config.json
dev/src/Exercism/BowlingTest.class.st
dev/src/Exercism/BracketPush.class.st
dev/src/Exercism/Clock.class.st
dev/src/Exercism/ClockTest.class.st
dev/src/Exercism/TwelveDays.class.st
dev/src/Exercism/TwelveDaysTest.class.st
dev/src/ExercismWIP/TwelveDays.class.st
exercises/bowling/BowlingTest.class.st
exercises/bracket-push/.meta/solution/BracketPush.class.st
exercises/clock/.meta/hints.md
exercises/clock/.meta/solution/Clock.class.st
exercises/clock/ClockTest.class.st
exercises/clock/README.md
exercises/twelve-days/.meta/hints.md
exercises/twelve-days/.meta/solution/TwelveDays.class.st
exercises/twelve-days/README.md
exercises/twelve-days/TwelveDaysTest.class.st

A simple one, with room for removing repetition with just a bit of code.
For the next one, I will take care of the metadata stuff myself :-)

242 add a solution for the twelve days exercise (exercism#242)

---

.gitattributes
.travis.yml
config.json
dev/src/Exercism/SieveTest.class.st
dev/src/Exercism/WordCountTest.class.st
dev/src/ExercismDev/ExercismManager.extension.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/STONJSONWriter.class.st
exercises/sieve/SieveTest.class.st
exercises/word-count/WordCountTest.class.st

Change the config template to active

Flip the active switch

---

config.json

As per request from @iHiD and review from @ErikSchierboom, the previous suggestions have been tested and this is a single toggle live flag change

Post feedback from live request, changes tested, and now simply toggle the flat

---

config.json
dev/src/Exercism/AtbashCipher.class.st
dev/src/Exercism/AtbashCipherTest.class.st
dev/src/ExercismWIP/AtbashCipher.class.st
exercises/atbash-cipher/.meta/hints.md
exercises/atbash-cipher/.meta/solution/AtbashCipher.class.st
exercises/atbash-cipher/AtbashCipherTest.class.st
exercises/atbash-cipher/README.md

Another contribution from @raydeejay

262 add a solution for the atbash cipher exercise

---

config.json
dev/src/Exercism/Diamond.class.st
dev/src/Exercism/DiamondTest.class.st
dev/src/ExercismWIP/Diamond.class.st
exercises/diamond/.meta/hints.md
exercises/diamond/.meta/solution/Diamond.class.st
exercises/diamond/DiamondTest.class.st
exercises/diamond/README.md

Another contribution from @raydeejay

265 add a solution for the diamond exercise

---

config.json
dev/src/Exercism/CollatzConjecture.class.st
dev/src/Exercism/CollatzConjectureTest.class.st
dev/src/ExercismWIP/CollatzConjecture.class.st
exercises/collatz-conjecture/.meta/hints.md
exercises/collatz-conjecture/.meta/solution/CollatzConjecture.class.st
exercises/collatz-conjecture/CollatzConjectureTest.class.st
exercises/collatz-conjecture/README.md

264 add a solution for the collatz conjecture exercise

---

README.md

Update README for post track launch

---

dev/src/Exercism/BowlingTest.class.st
dev/src/Exercism/CollatzConjectureTest.class.st
dev/src/Exercism/ForthTest.class.st
dev/src/Exercism/GrainsTest.class.st
dev/src/ExercismDev/ExercismExerciseGenerator.class.st
dev/src/ExercismWIP/AffineCipherTest.class.st
dev/src/ExercismWIP/AllYourBaseTest.class.st
dev/src/ExercismWIP/BinarySearchTest.class.st
dev/src/ExercismWIP/ChangeTest.class.st
dev/src/ExercismWIP/GoCountingTest.class.st
dev/src/ExercismWIP/LargestSeriesProductTest.class.st
dev/src/ExercismWIP/NthPrimeTest.class.st
dev/src/ExercismWIP/NucleotideCountTest.class.st
dev/src/ExercismWIP/OcrNumbersTest.class.st
dev/src/ExercismWIP/PalindromeProductsTest.class.st
dev/src/ExercismWIP/PerfectNumbersTest.class.st
dev/src/ExercismWIP/PhoneNumberTest.class.st
dev/src/ExercismWIP/QueenAttackTest.class.st
dev/src/ExercismWIP/SatelliteTest.class.st
dev/src/ExercismWIP/SayTest.class.st
dev/src/ExercismWIP/SeriesTest.class.st
dev/src/ExercismWIP/SgfParsingTest.class.st
dev/src/ExercismWIP/VariableLengthQuantityTest.class.st
dev/src/ExercismWIP/WordyTest.class.st
exercises/bowling/BowlingTest.class.st
exercises/collatz-conjecture/CollatzConjectureTest.class.st
exercises/forth/ForthTest.class.st
exercises/grains/GrainsTest.class.st

Convert incorrect use of Exception catching, to Error catching

---

docs/INSTALLATION.md
docs/LEARNING.md
docs/RESOURCES.md

(very wip, but driven from seasoned exercism maintainer). Cleaned up discord link (which had changed)

Added preliminary instructions for linux hackers 

---

dev/src/ExercismDev/ExercismExerciseGenerator.class.st

Fixes #322 First test should direct students to read class comment

322-First-test-should-direct-students-to-read-class-comment

---

dev/src/ExercismTests/ExercismExerciseTest.class.st
dev/src/ExercismTests/ExercismPackageTest.class.st
dev/src/ExercismTools/ClyExercismSubmitCommand.class.st
dev/src/ExercismTools/ExercismExercise.class.st
dev/src/ExercismTools/RPackage.extension.st
dev/src/ExercismTools/RPackageTag.extension.st

Issue reported by @RoelofWobben - can't submit a legacy exercise due to removal of Exercism parent package

Better legacy exercise support

---

dev/src/ExercismTools/ClassDescription.extension.st
dev/src/ExercismTools/ClyExercismShareCommand.class.st
dev/src/ExercismTools/ExercismHttpClient.class.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/RPackage.extension.st
dev/src/ExercismTools/String.extension.st

Something for @RoelofWobben to try when asking for help.
Doesn't quite work as ";" seems to cause the source to get cut off?

Experiment to share code on dpaste

---

dev/src/ExercismDev/ExercismManager.extension.st
dev/src/ExercismTools/ClassDescription.extension.st
dev/src/ExercismTools/ClyExercismFetchCommand.class.st
dev/src/ExercismTools/ClyExercismProgressCommand.class.st
dev/src/ExercismTools/ClyExercismShareCommand.class.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/RPackage.extension.st
dev/src/ExercismTools/RPackageTag.extension.st

Fix issue with images upgraded but still have Exercism package

Confirm sharing is ok, don't print default class comment

---

docs/exercism-api.md

Swap terminology of exercise name with 'slug'

---

dev/src/BaselineOfExercism/BaselineOfExercism.class.st

Add Exercism logo to World

---

exercises/practice/die/.docs/instructions.append.md
exercises/practice/die/.docs/instructions.md

This was an exercise contributed from the Pharo community. It's not in the 'official' list of exercises so I think it never got a proper description.
This is to help fix the configlet error on #467.

Create Die exercise instructions

---

README.md
docs/INSTALLATION.md
docs/UPGRADE.md

Fixes #466 by specifying main branch

Fixes #466 by specifying main branch

---

README.md

Related to PR #474. This is to explain why we still need a `master` branch and what should be done with it.

Add information on installation issue workaround

---

exercises/practice/hello-world/HelloWorld.class.st

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

dev/src/BaselineOfExercism/BaselineOfExercism.class.st
dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismTests/ExercismConfigGeneratorTest.class.st
dev/src/ExercismTests/ExercismGeneratorTest.class.st
dev/src/ExercismTests/FailedTestOSProcess.class.st
dev/src/ExercismTests/MockTestOSProcess.class.st
dev/src/ExercismTests/SuccessfulTestOSProcess.class.st
docs/INSTALLATION.md

Fix pharo9 dev baseline

---

dev/src/ExercismTools/ExercismManager.class.st

Now the link points to the right page.
fixes; #507

Fix track Progress menu choice 

---

dev/src/ExercismTests/ExercismPackageTest.class.st

fixes #509 - Failing test on ExercismPackageTest

---

dev/src/ExercismTests/TestResultTest.extension.st
dev/src/ExercismTools/TestResult.extension.st

- added information about OS, platform, Image version, VM version
- added unit tests for test result summary content
- fixes #518

Embraced test result summary output with information about environment

---

dev/src/ExercismTools/ExercismHttpClient.class.st

Fixed sending of deprecated message

---

exercises/practice/reverse-string/.docs/instructions.append.md

Changes:
- fix singular/plural mismatches

minor grammar tweaks

---

dev/src/Exercise@ResistorColorDuo/ResistorColorDuo.class.st

Make colorValue: method more readable

---

dev/src/BaselineOfExercism/BaselineOfExercism.class.st
dev/src/ExercismPharo90/StDebugger.extension.st
dev/src/ExercismPharo90/package.st

- added compatibility package for P9 and included in Exercism baseline
- fixes #503

Backported create class method from debugger  from P10 to P9

---

.github/workflows/ci.yml
dev/src/BaselineOfExercism/BaselineOfExercism.class.st
dev/src/ExercismMocking/Any.extension.st

- removed dependency on concrete version tag
- changed Pharo version to use latest stable release
- fixes #527

Updated Smalltalk CI GH workflow action

---

config.json

Added key features for Pharo track, tags updated

---

docs/LEARNING.md

Updated LEARNING.md with PBE9

---

config.json

fixed typos in key features description

---

dev/src/BaselineOfExercism/BaselineOfExercism.class.st
dev/src/ExercismPharo80/Path.extension.st
dev/src/ExercismPharo80/package.st

Added backward compatibility for Pharo 8

---

dev/src/BaselineOfExercism/BaselineOfExercism.class.st
dev/src/Exercise@ExampleAllFail/ExampleAllFailTest.class.st
dev/src/Exercise@ExampleAllFail/package.st
dev/src/Exercise@ExampleAllPass/ExampleAllPassTest.class.st
dev/src/Exercise@ExampleAllPass/package.st
dev/src/Exercise@ExampleAllRaiseError/ExampleAllRaiseErrorTest.class.st
dev/src/Exercise@ExampleAllRaiseError/package.st
dev/src/Exercise@ExampleEmptySolutionClass/ExampleEmptySolutionClass.class.st
dev/src/Exercise@ExampleEmptySolutionClass/ExampleEmptySolutionClassTest.class.st
dev/src/Exercise@ExampleEmptySolutionClass/package.st
dev/src/Exercise@ExampleEmptySolutionFile/ExampleEmptySolutionFileTest.class.st
dev/src/Exercise@ExampleEmptySolutionFile/package.st
dev/src/Exercise@ExampleErrorFailPass/ExampleErrorFailPassTest.class.st
dev/src/Exercise@ExampleErrorFailPass/package.st
dev/src/Exercise@ExampleExtensionMethod/ExampleExtensionMethodTest.class.st
dev/src/Exercise@ExampleExtensionMethod/package.st
dev/src/Exercise@ExampleSyntaxError/ExampleSyntaxErrorTest.class.st
dev/src/Exercise@ExampleSyntaxError/package.st
dev/src/Exercise@ExampleTypoInMethodName/ExampleTypoInMethodNameTest.class.st
dev/src/Exercise@ExampleTypoInMethodName/package.st
dev/src/ExercismTestRunner/ExercismTestRunner.class.st
dev/src/ExercismTestRunnerTests/ExercismTestRunnerTest.class.st
dev/src/ExercismTestRunnerTests/TestRunnerExampleGenerator.class.st
dev/src/ExercismTools/ExercismExercise.class.st

Change import of sources to image so that example solutions are removed prior import of student solution
- added unit test to check reming solution classes
- added example (golden) test to test empty class definition with no method defined and example present in image
- moved example (golden) tests to separate packages
- fixes #576

Change import of sources to image so that example solutions are removed

---

dev/src/ExercismTestRunner/ExercismTestRunner.class.st
dev/src/ExercismTestRunnerTests/ExercismTestRunnerTest.class.st

579 test runner should exit with zero code

---

dev/src/ExercismTestRunner/TestResult.extension.st

Fix of  overall test runner status

---

exercises/practice/grade-school/.docs/instructions.append.md

Correct grammar in instructions.append.md

---

dev/src/ExercismTestRunner/ExercismTestRunner.class.st
dev/src/ExercismTestRunnerTests/ExercismTestRunnerTest.class.st
dev/src/ExercismTests/ExercismExerciseTest.class.st
dev/src/ExercismTools/ExercismExercise.class.st

Fixed removal of exercise sources befor running test runner.

---

dev/src/Exercise@ExampleAllFail/ExampleAllFailTest.class.st
dev/src/Exercise@ExampleAllPass/ExampleAllPassTest.class.st
dev/src/Exercise@ExampleAllRaiseError/ExampleAllRaiseErrorTest.class.st
dev/src/Exercise@ExampleEmptySolutionClass/ExampleEmptySolutionClassTest.class.st
dev/src/Exercise@ExampleEmptySolutionFile/ExampleEmptySolutionFileTest.class.st
dev/src/Exercise@ExampleErrorFailPass/ExampleErrorFailPassTest.class.st
dev/src/Exercise@ExampleExtensionMethod/ExampleExtensionMethodTest.class.st
dev/src/Exercise@ExampleSyntaxError/ExampleSyntaxErrorTest.class.st
dev/src/Exercise@ExampleTypoInMethodName/ExampleTypoInMethodNameTest.class.st

This is fix for golden tests in test runner repository (it uses code from this repository). Once I will move test runner code to test runner repository,  I will remove test runner packages from this repository.

Fixed constructor for test exercises of golden tests.

---

dev/src/ExercismDev/ExercismExerciseGenerator.class.st
dev/src/ExercismTests/ExercismExerciseGeneratorTest.class.st
dev/src/ExercismTools/ExercismExercise.class.st
dev/src/ExercismTools/ExercismTest.class.st

Added title generation from exercise problem specification metadata

---

dev/src/ExercismTests/ExercismDownloadCommandTest.class.st
dev/src/ExercismTests/ExercismReviewCommandTest.class.st
dev/src/ExercismTests/ExercismTonelReaderTest.class.st
dev/src/ExercismTools/ExercismSubmission.class.st
dev/src/ExercismTools/ExercismTonelReader.class.st
dev/src/ExercismTools/TonelReader.extension.st

664 gigasecond exercise cannot loadignore stub file
