.travis.yml

I missed this when bootstrapping.

Fix flag name in lint command for Travis CI

---

dev/src/ExercismTools/ExercismManager.class.st

As tonel writer blows away the directory - we need to preserve the solution meta data

Backup the exercism meta info when submitting

---

dev/src/BaselineOfExercism/BaselineOfExercism.class.st
dev/src/ExercismTools/ExercismManager.class.st

As per @bencoman suggestion - pulls in a web browser package that should work on all OS's (and ultimately might chop the legs of OSProcess)

Adds support for an OS agnostic web browser

---

dev/src/ExercismTools/AbstractNautilusUI.extension.st
dev/src/ExercismTools/ExercismDownload.class.st
dev/src/ExercismTools/ExercismSubmit.class.st
dev/src/ExercismTools/ExercismSubmitTest.class.st

We need somewhere to store the exercise metadata to be used by Submit command.  Some options are: 
- as a class comment
- as a special method
- a Manifest-like class
- in the package's "Properties" class variable
I'd first like to try the last one since it has the least visual distraction for students.
To test this PR...
1. Create an empty "Exercism" package
2. Right-click on "Exercism" package > Exercism > Fetch Exercise = hello-world
3. Right click on "HelloWorld" tag> Exercism > View metadata

Store metadata in package "Properties" class var.

---

dev/src/ExercismTools/ExercismCommand.class.st
dev/src/ExercismTools/ExercismDownload.class.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/ExercismSubmit.class.st
dev/src/ExercismTools/ExercismSubmitTest.class.st
dev/src/ExercismTools/String.extension.st
dev/src/ExercismTools/TonelWriter.extension.st

I broadly understand what this thing needs to do now. I won't be able to spend anytime on this tomorrow so I'm placing this pull request here to make sure I'm on the right track. Hopefully I'll be able to get back to it this weekend.
This is definitely a work in progress. A few more helper methods will probably be made, plus getting rid of some hard coded values. 
I used the Acronym exercise as an example, which means I could not test submitting because I have not downloaded the exercise metadata, which I can't do because I haven't unlocked the exercise ¯\_(ツ)_/¯ .
I've left a few comments in the source code with my thoughts and a few problems I haven't yet solved. Let me know what you think.
I'm also irritates me that I don't have any tests of the public interface. For lack of a good …

Issue 96: Submit exercises via HTTP patch method

---

dev/src/ExercismTools/ClyExercismCommand.class.st
dev/src/ExercismTools/ExercismManager.class.st
dev/src/ExercismTools/ExercismManagerTest.class.st

Allow users to simply paste the provided exercism command line instructions into the fetch dialog (as well as the kebab case exercise name). This makes it simpler to follow the instructions on the website.
(cherry picked from commit 86e9467) - to provide a clean diff

128-Adds simple parsing for exercise name

---

dev/src/ExercismTools/ClyExercismExerciseCommand.class.st
dev/src/ExercismTools/ClyExercismMetaDataCommand.class.st
dev/src/ExercismTools/ClyExercismPkgFetchCommand.class.st
dev/src/ExercismTools/ClyExercismProgressCommand.class.st
dev/src/ExercismTools/ClyExercismSubmitCommand.class.st
dev/src/ExercismTools/ClyExercismTagFetchCommand.class.st

… improve the ordering and provide a fetch menu at both the exercise and project level (so its less annoying to click on the right place.  *we may change fetch on the exercise level to fetch next as we could have the meta info in the image).
(cherry picked from commit 5a0b684)
This PR is a second attempt to do this cleanly due to forked repo shenanigans

Improve the menu's for exercism by cleaning up to use instance side methods

---

dev/src/Exercism/LeapTest.class.st
dev/src/Exercism/ReverseStringTest.class.st
dev/src/ExercismTools/ExercismTest.class.st
dev/src/ExercismTools/ExercismTestTest.class.st

This fixes #142 and provides a generic way for tests to scan for misused selectors.

Scan solutions for known selectors that the student was asked to avoid

---

dev/src/ExercismDev/ClyExercismReviewSummaryCommand.class.st

fixing the bad inheritance of menu items, cause this menu to break

Fix missing "View Summary" menu item in mentor menu

---

dev/src/Exercise@AtbashCipher/AtbashCipher.class.st

Fixes #324 AtbashCipher >> splitInGroupsOfFive:

324-AtbashCipher--splitInGroupsOfFive

---

docs/exercism-api.md

Fixes #281.
This is work in progress for the moment. 
I've started with fetching exercises for now. Documenting the details of a `200` response is a bit difficult for me. I'm not that familiar with REST APIs and trying to get an idea of what it would look like from reading our own code is hard too.
Checking the exercism website source code has been very useful for getting the range of possible responses.
More to follow in this PR. The details of a `200` response need to be written and submitting exercises needs to be documented.

Document exercism API

---

dev/src/Exercise@TwelveDays/TwelveDays2.class.st
dev/src/Exercise@TwelveDays/TwelveDays2Test.class.st
dev/src/Exercise@TwelveDays/TwelveDaysTest.class.st

Here is how an alternative solution to Twelve Days might look based on the solution shown in #386. The biggest change is that `#verse:` is swapped out for `#getVerse:` (might keep the name the same if we use this solution). `#verses` and `#dayName` are direct copies of the first solutions `#gifts` and `#ordinal:` respectively, the names just changed to fit in with the alternate solution. 
The big point of this solution is that it uses `SequencableCollection#>>joinUsing:last:` in `#getVerse`.
Let me know if you want to go ahead with this.

Add alternative solution to TwelveDays exercise

---

dev/src/ExercismTools/ClyExercismCommand.class.st
dev/src/ExercismTools/ClyExercismExerciseCommand.class.st
dev/src/ExercismTools/ClyExercismFetchCommand.class.st
dev/src/ExercismTools/ClyExercismMenuGroup.class.st
dev/src/ExercismTools/ClyExercismProgressCommand.class.st
dev/src/ExercismTools/ClyExercismShareCommand.class.st
dev/src/ExercismTools/ClyExercismSubmitCommand.class.st

Fixes #397.
Here I have expanded the documentation on the class comments across the package. This is something to help my own understanding of the code base and to help anyone else who may be unfamiliar too.
I've used Markdown format for the comments. Also I shifted `ClyExercismCommand>>#prepareFullExecutionInContext:` into the `execution` protocol/category to match the super class.
Let me know if you think there is anything I can add here or if anything needs changing.
Also I understand that all of us may be too busy at times with life outside of Github to review each pull request or issue. If it is OK with you I think it is a good idea to allow maintainers to merge pull requests and close issues with no further review from others if no one else has the time available. That way we can …

Document ExercismTools Menu classes

---

bin/fetch-configlet

This seems to be a problem across many [tracks](https://github.com/exercism/configlet/issues/173). The changes here are based of those in the [Rust track](https://github.com/exercism/rust/pull/929/files). I've chosen that particular one because I can understand what the changes do.
The [original source](https://github.com/exercism/configlet/blob/master/scripts/fetch-configlet) `fetch-configlet` script has a lot of differences that are currently beyond my understanding.

Fix broken fetch-configlet script

---

docs/LEARNING.md

The link is updated to the same as that on the http://pharo.org/community page.

Update broken Discord invite link

---

dev/src/ExercismDev/ExercismGenerator.class.st
dev/src/ExercismTests/ExercismGeneratorTest.class.st

Previous work made `ExercismGenerator>>#generateTo:` redundant. This change allows it to be safely
removed.
Storing the default path for exercises in a class variable proved to be problematic when it is mutable. In tests 
it could be overridden with a memory file system. When an attempt is then made to write exercises in production
the same memory file reference would be used. This will at the least be unintentional and possibly cause an 
error. The class variable could be reset in the test tear down but I believe the better option is to not allow 
the class variable to be mutated at all. I've removed mutation of the class variable in the tests and now 
`ExercismGenerator` has a `exercisesPath` instance variable instead of references to the class variable.
In a previous commit I made the …

Remove redundant `ExercismGenerator>>#generateTo:` method

---

dev/src/ExercismTools/TExercise.trait.st

This is more work to enable [this issue](https://github.com/exercism/v3/issues/2264). 
As I'm working on making V3 exercise generation possible I'm finding I need a lot of prerequisites in place. To help keep exercise generation under test coverage I need at least one V3 exercise to be implemented to use in the tests. To do that I need an exercise test case with the exercise meta data. That's what this commit is for.
@exercism/reviewers please review this.

Allow test cases to carry exercise meta data

---

dev/src/BaselineOfExercism/BaselineOfExercism.class.st
dev/src/ExercismV3/SourceImporter.class.st
dev/src/ExercismV3/package.st

The intention is to create the code supporting Exercism version 3 (V3) from a clean start. Refactoring
V2 code has proven too large a task.
With a V3 baseline we can load the code and dependencies into the image without any V2 code cluttering
things up. This also allows us to keep development of both versions in the same repository.
`SourceImporter` is just a class stub so that the baseline contains something and we can verify that it
loads correctly.
The V3 baseline can be loaded using Iceberg:  In the repositories window, right click on the 
`pharo-smalltalk` repository -> mouse over `Metacello` -> left click on `Install baseline of Exercism...`
-> enter `v3` into the text field -> left click the `OK` button.

Create Exercism V3 baseline

---

.github/workflows/ci.yml
config.json

CI failures on #467 raised some possible outdated CI configuration. This is to fix the incorrect configlet usage.

Remove outdated configlet usage from CI tasks

---

dev/src/ExercismTests/ExercismSubmissionTest.class.st
dev/src/ExercismTools/ExercismSubmission.class.st

Fixes #500 and #499 
- necessitated a decoupling of the files from the valid files; the iterator now only uses the content dict for both filenames and contents

ExercismSubmission will ignore files with no content

---

dev/src/ExercismSystemTests/ExercismHttpClientTest.class.st

broken as it was asserting on something that wasn't in the current Google response
Frankly these tests shouldn't really exist; suggest injecting a ZnClient into an ExercismClient and then mocking behaviours we care about

fix the generic get test

---

dev/src/Exercise@Allergies/Allergies.class.st

I'd like to use more specific  ApplicationError, but "domain" seems strongly tied to mathematics from than application when the class description is considered...
```
I am DomainError, an ArithmeticException indicating that some argument 
falls outside an expected domain, [from, to] When my valid interval is left- or right-open, 
use signal: creation protocol to provide a custom messageText rather than the default [from, to] notation.
```

[Allergies] Use plain Error

---

dev/src/ExercismTests/ExercismExerciseTest.class.st
dev/src/ExercismTools/ExercismExercise.class.st

This makes mentoring easier, particularly when there are multiple iterations in the student's exercise solution.
Currently: 
With this change:

Upon submission, the TestResults will be the last file

---

dev/src/ExercismDev/ExercismReviewCommand.class.st
dev/src/ExercismTests/ExercismDownloadCommandTest.class.st
dev/src/ExercismTests/ExercismReviewCommandTest.class.st
dev/src/ExercismTests/ExercismSubmissionTest.class.st
dev/src/ExercismTools/ExercismDownloadCommand.class.st
dev/src/ExercismTools/ExercismFetchCommand.class.st
dev/src/ExercismTools/ExercismSubmission.class.st

- fixes #409 
- this will effectively resolve loading exercise, where source files contain dependent classes (one class is subclass of another)
- Tonel format used in Pharo uses one file per class for serialization from/to git
- When subclass is loaded earlier than superclass, there was a problem with dependency
- New way uses MCSnapshot object, that resolves dependencies between class definitions and classes are loaded in proper order

409-Resolves problem with loading dependent classes within package(exercise)

---

config.json

This enables Test Runner for Pharo track.
Should be merged after (follow-up of): https://github.com/exercism/pharo-smalltalk-test-runner/pull/18

Enable test runner for Pharo track

---

dev/src/ExercismDev/ExercismExerciseGenerator.class.st
docs/CONTRIBUTING.md

Following changes make Exercise test generator working again. Previously it resulted in error and therefore test classes cannot be generated from canonical descriptions.

Fix exercise test generator

---

dev/src/ExercismDev/ExercismExerciseGenerator.class.st
dev/src/ExercismDev/ExercismTestMethodGenerator.class.st
dev/src/ExercismTests/ExercismExerciseGeneratorTest.class.st

Generation of test class, its cases from problem specifications.
- added pragmas with test case metadata
- otherwise result should be same as original implementation

Refactoring of ExercismExerciseGenerator

---

dev/src/Exercise@ResistorColorDuo/ResistorColorDuoTest.class.st
exercises/practice/resistor-color-duo/.docs/instructions.md
exercises/practice/resistor-color-duo/.meta/tests.toml
exercises/practice/resistor-color-duo/ResistorColorDuoTest.class.st

594 out of sync unit tests for resistor color duo

---

dev/src/BaselineOfExercism/BaselineOfExercism.class.st
dev/src/ExercismPharo110/Class.extension.st
dev/src/ExercismPharo110/package.st
dev/src/ExercismTestRunner/ExercismTest.extension.st
dev/src/ExercismTools/Class.extension.st

610 all pharo tests pass even though i didnt solve the exercise

---

dev/src/ExercismTools/TonelParser.extension.st

Added guard clause for seting readstream position, when not changed.

---

dev/src/BaselineOfExercism/BaselineOfExercism.class.st

I used wrong package for dependency therefore fix was not applied / loaded for Pharo 11
- fixes #610

Fixed dependency in project baseline to be loaded in P11

---

dev/src/Exercise@CircularBuffer/CircularBufferTest.class.st
exercises/practice/circular-buffer/CircularBufferTest.class.st

I noticed two typos in this test file.

Fix typos in `CircularBufferTest.class.st`

---

dev/src/ExercismTools/ExercismExercise.class.st

Follow-up on previous PR. 
Removing classes and methods are not enough (classes and methods are moved to anonymous package), therefore it still needs to be removed from system.
- fixes #630

Removed classes and methods from package still needs to be removed

---

dev/src/Exercise@Etl/EtlTest.class.st
dev/src/Exercise@IsbnVerifier/IsbnVerifierTest.class.st
dev/src/Exercise@OcrNumbers/OcrNumbersTest.class.st
dev/src/Exercise@SumOfMultiples/SumOfMultiplesTest.class.st
dev/src/Exercise@TwoFer/TwoFerTest.class.st

Some exercise names (who use capital letter abbreviations) were out-of-sync with config.json. Now config.json should be generated according to titles in problem specifications.
Also fixed out-of-sync UUID of OCR Numbers exercise.

Sync exercise titles capitals
